In [1]:
import gensim.downloader as api

wv = api.load("word2vec-google-news-300")

In [2]:
wv.similarity(w1="great", w2 = "good")

np.float32(0.729151)

In [3]:
wv_great = wv["great"]
wv_good = wv["good"]

In [5]:
import pandas as pd

df = pd.read_csv(r"D:\Data_Science\NLP\Season2\combined_news_dataset.csv")

In [6]:
df.head()

                                                text label
0  WASHINGTON (Reuters) - The head of a conservat...  true
1  WASHINGTON (Reuters) - Transgender people will...  true
2  WASHINGTON (Reuters) - The special counsel inv...  true
3  WASHINGTON (Reuters) - Trump campaign adviser ...  true
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  true

In [7]:
df.label.value_counts()

label
true    4999
fake    4999
Name: count, dtype: int64

In [8]:
df["label_num"] = df.label.map({"fake": 0, "true": 1})

In [9]:
df.head()

                                                text label  label_num
0  WASHINGTON (Reuters) - The head of a conservat...  true          1
1  WASHINGTON (Reuters) - Transgender people will...  true          1
2  WASHINGTON (Reuters) - The special counsel inv...  true          1
3  WASHINGTON (Reuters) - Trump campaign adviser ...  true          1
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  true          1

In [10]:
import spacy
nlp = spacy.load("en_core_web_lg")

def preprocess_and_vectorize(text):
    doc = nlp(text)
    
    filtered_tokens = []
    for token in doc:
        if token.is_punct or token.is_stop:
            continue
        filtered_tokens.append(token.lemma_)
    return filtered_tokens

In [11]:
preprocess_and_vectorize("This is a great movie, I really enjoyed it!")

['great', 'movie', 'enjoy']

In [12]:
wv.get_mean_vector(["great", "movie", "enjoyed"], pre_normalize=False)[:3]

array([ 0.05517578,  0.06738281, -0.16605632], dtype=float32)

In [14]:
df["vector"] = df["text"].apply(lambda text: preprocess_and_vectorize(text))

KeyboardInterrupt:

In [ ]:

from sklearn.model_selection import train_test_split


#Do the 'train-test' splitting with test size of 20% with random state of 2022 and stratify sampling too
X_train, X_test, y_train, y_test = train_test_split(
    df.vector.values, 
    df.label_num, 
    test_size=0.2, # 20% samples will go to test dataset
    random_state=2022,
    stratify=df.label_num
)

In [ ]:
import numpy as np


print("Shape of X_train before reshaping: ", X_train.shape)
print("Shape of X_test before reshaping: ", X_test.shape)


X_train_2d = np.stack(X_train)
X_test_2d =  np.stack(X_test)

print("Shape of X_train after reshaping: ", X_train_2d.shape)
print("Shape of X_test after reshaping: ", X_test_2d.shape)

Shape of X_train before reshaping:  (7998,)
Shape of X_test before reshaping:  (2000,)

ValueError: all input arrays must have the same shape

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report

#1. creating a GradientBoosting model object
clf = GradientBoostingClassifier()

#2. fit with all_train_embeddings and y_train
clf.fit(X_train_2d, y_train)


#3. get the predictions for all_test_embeddings and store it in y_pred
y_pred = clf.predict(X_test_2d)


#4. print the classfication report
print(classification_report(y_test, y_pred))

In [ ]:
test_news = [
    "WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a Ã¢â‚¬Å“fiscal conservativeÃ¢â‚¬Â on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBSÃ¢â‚¬â„¢ Ã¢â‚¬Å“Face the Nation,Ã¢â‚¬Â drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense Ã¢â‚¬Å“discretionaryÃ¢â‚¬Â spending on programs that support education, scientific research, infrastructure, public health and environmental protection. Ã¢â‚¬Å“The (Trump) administration has already been willing to say: Ã¢â‚¬ËœWeÃ¢â‚¬â„¢re going to increase non-defense discretionary spending ... by about 7 percent,Ã¢â‚¬â„¢Ã¢â‚¬Â Meadows, chairman of the small but influential House Freedom Caucus, said on the program. Ã¢â‚¬Å“Now, Democrats are saying thatÃ¢â‚¬â„¢s not enough, we need to give the government a pay raise of 10 to 11 percent. For a fiscal conservative, I donÃ¢â‚¬â„¢t see where the rationale is. ... Eventually you run out of other peopleÃ¢â‚¬â„¢s money,Ã¢â‚¬Â he said. Meadows was among Republicans who voted in late December for their partyÃ¢â‚¬â„¢s debt-financed tax overhaul, which is expected to balloon the federal budget deficit and add about $1.5 trillion over 10 years to the $20 trillion national debt. Ã¢â‚¬Å“ItÃ¢â‚¬â„¢s interesting to hear Mark talk about fiscal responsibility,Ã¢â‚¬Â Democratic U.S. Representative Joseph Crowley said on CBS. Crowley said the Republican tax bill would require the  United States to borrow $1.5 trillion, to be paid off by future generations, to finance tax cuts for corporations and the rich. Ã¢â‚¬Å“This is one of the least ... fiscally responsible bills weÃ¢â‚¬â„¢ve ever seen passed in the history of the House of Representatives. I think weÃ¢â‚¬â„¢re going to be paying for this for many, many years to come,Ã¢â‚¬Â Crowley said. Republicans insist the tax package, the biggest U.S. tax overhaul in more than 30 years,  will boost the economy and job growth. House Speaker Paul Ryan, who also supported the tax bill, recently went further than Meadows, making clear in a radio interview that welfare or Ã¢â‚¬Å“entitlement reform,Ã¢â‚¬Â as the party often calls it, would be a top Republican priority in 2018. In Republican parlance, Ã¢â‚¬Å“entitlementÃ¢â‚¬Â programs mean food stamps, housing assistance, Medicare and Medicaid health insurance for the elderly, poor and disabled, as well as other programs created by Washington to assist the needy. Democrats seized on RyanÃ¢â‚¬â„¢s early December remarks, saying they showed Republicans would try to pay for their tax overhaul by seeking spending cuts for social programs. But the goals of House Republicans may have to take a back seat to the Senate, where the votes of some Democrats will be needed to approve a budget and prevent a government shutdown. Democrats will use their leverage in the Senate, which Republicans narrowly control, to defend both discretionary non-defense programs and social spending, while tackling the issue of the Ã¢â‚¬Å“Dreamers,Ã¢â‚¬Â people brought illegally to the country as children. Trump in September put a March 2018 expiration date on the Deferred Action for Childhood Arrivals, or DACA, program, which protects the young immigrants from deportation and provides them with work permits. The president has said in recent Twitter messages he wants funding for his proposed Mexican border wall and other immigration law changes in exchange for agreeing to help the Dreamers. Representative Debbie Dingell told CBS she did not favor linking that issue to other policy objectives, such as wall funding. Ã¢â‚¬Å“We need to do DACA clean,Ã¢â‚¬Â she said.  On Wednesday, Trump aides will meet with congressional leaders to discuss those issues. That will be followed by a weekend of strategy sessions for Trump and Republican leaders on Jan. 6 and 7, the White House said. Trump was also scheduled to meet on Sunday with Florida Republican Governor Rick Scott, who wants more emergency aid. The House has passed an $81 billion aid package after hurricanes in Florida, Texas and Puerto Rico, and wildfires in California. The package far exceeded the $44 billion requested by the Trump administration. The Senate has not yet voted on the aid."
    "Donald Trump s team certainly doesn t make it easy for the people who have to interview them. In a typical interview with Trump s team, news anchors have to constantly fact check and repeatedly bring Trump s minions back to the original questions and topics as they deflect blame and avoid answering every question.On Monday s  New Day,  CNN host Alisyn Camerota had to interview Trump spokesman Sean Spicer, and it was basically an interview from hell as Spicer wouldn t give her any responses to the most pressing questions. Camerota had tried to ask Spicer just what special information Trump claimed he knows about Russia s involvement in the US election. Spicer s response couldn t have been more insane as he said Trump gets a lot of  classified information, intelligence reports  on a daily basis (despite the fact that Trump s team once said the president-elect only gets briefings once per week). Spicer then went off topic and said Trump will wait to make conclusions about the hacking, ignoring the fact that Trump has defended Russia extensively from all blame.Camerota was unwilling to let Spicer avoid the question, and she said: I want to get back to my question. Is Mr. Trump, who said he s going to reveal something, he says he knows things. Spicer again refused to give a response, stating that Trump would talk about it himself right before blaming Obama for not talking about China s 2015 hacking. Camerota responded by fact-checking Spicer right then and there. She said: Sean, just to correct you, you say not a single statement was ever issued or made after the Chinese hacking. I have the statement right here in my hands. Spicer s response was pathetic, as he admitted to being wrong but still continued to blame Obama, accusing Obama of responding too late. Camerota tirelessly tried to bring Spicer back to her question: Sean, I m more interested in what Mr. Trump is going to do. We re not electing President Obama again. You are representing Mr. Trump. Camerota asked about Trump s plans, and Spicer couldn t provide her with anything. All he did was confess that Trump didn t have a final report. Spicer then stunned Camerota by admitting that he had lied earlier when he said Trump had been briefed: The report is not final. He s not been briefed by the heads of the intelligence community. A stunned Camerota said in disbelief,  He has not been briefed about the heads of the intelligence community about whether or not they believe Russia is behind the hacking? Spicer began to fall apart when Camerota told him to  hold on  after he accused anyone who believed  non-final  reports of being irresponsible. Spicer shouted, No! Not, hold on! The idea we re asking people and making assumptions on a report that s not final is unbelievable. The rest of the interview, Camerota was forced to constantly counter Spicer s moronic remarks. Spicer practically ended the interview by completely disrespecting Camerota for expecting that Trump and his team might at least be exploring the possibility that reports about the Russian hacking are correct. Spicer said condescendingly: I know it s frustrating for you that we re doing it in a logical way. No, we re going to get all the information, get briefed properly and make a decision. We re not going to put the cart before the horse. Camerota couldn t believe her ears. You can watch this disastrous interview below:Featured image via screenshot"
]

test_news_vectors = [preprocess_and_vectorize(n) for n in test_news]
clf.predict(test_news_vectors)

In [ ]:
#finally print the confusion matrix for the best model (GradientBoostingClassifier)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


from matplotlib import pyplot as plt
import seaborn as sn
plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Prediction')
plt.ylabel('Truth')