Disadvantages:
1. It may consume too much memory and computing resources.

2. Does not capture meaning of the words properly.

In [7]:
import pandas as pd
import numpy as np
import sklearn

In [3]:
df = pd.read_csv('spam (1).csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['spam'] = df.Category.apply(lambda x: 1 if x == 'spam' else 0)

In [10]:
df.shape

(5572, 3)

In [6]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [11]:
X_train.shape

(4457,)

In [12]:
X_test.shape

(1115,)

In [14]:
type(X_train)

pandas.core.series.Series

In [15]:
X_train[:4]

3760    GOD ASKED, "What is forgiveness?" A little chi...
3821    I got arrested for possession at, I shit you n...
3210    Havent mus ask if u can 1st wat. Of meet 4 lun...
495                      Are you free now?can i call now?
Name: Message, dtype: object

In [16]:
type(y_train)

pandas.core.series.Series

In [13]:
y_train[:4]

3760    0
3821    0
3210    0
495     0
Name: spam, dtype: int64

In [22]:
X_train.values

array(['GOD ASKED, "What is forgiveness?" A little child gave lovely reply, "It is d wonderful fruit that a tree gives when it is being hurt by a stone.. Good night......',
       'I got arrested for possession at, I shit you not,  &lt;TIME&gt;  pm',
       'Havent mus ask if u can 1st wat. Of meet 4 lunch den u n him meet can already lor. Or u wan 2 go ask da ge 1st then confirm w me asap?',
       ...,
       'YES! The only place in town to meet exciting adult singles is now in the UK. Txt CHAT to 86688 now! 150p/Msg.',
       'Imagine you finally get to sink into that bath after I have put you through your paces, maybe even having you eat me for a while before I left ... But also imagine the feel of that cage on your cock surrounded by the bath water, reminding you always who owns you ... Enjoy, my cuck',
       'Do you know where my lab goggles went'],
      shape=(4457,), dtype=object)

In [21]:
type(X_train.values)

numpy.ndarray

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59184 stored elements and shape (4457, 7745)>

In [20]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7745))

In [23]:
X_train_cv.shape

(4457, 7745)

In [24]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'],
      shape=(7745,), dtype=object)

In [25]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [26]:
v.vocabulary_

{'god': 3167,
 'asked': 1118,
 'what': 7474,
 'is': 3751,
 'forgiveness': 2953,
 'little': 4164,
 'child': 1782,
 'gave': 3090,
 'lovely': 4240,
 'reply': 5714,
 'it': 3763,
 'wonderful': 7581,
 'fruit': 3027,
 'that': 6820,
 'tree': 7042,
 'gives': 3149,
 'when': 7481,
 'being': 1328,
 'hurt': 3561,
 'by': 1593,
 'stone': 6491,
 'good': 3187,
 'night': 4786,
 'got': 3204,
 'arrested': 1097,
 'for': 2941,
 'possession': 5323,
 'at': 1139,
 'shit': 6099,
 'you': 7707,
 'not': 4836,
 'lt': 4257,
 'time': 6907,
 'gt': 3265,
 'pm': 5263,
 'havent': 3365,
 'mus': 4659,
 'ask': 1116,
 'if': 3601,
 'can': 1633,
 '1st': 338,
 'wat': 7397,
 'of': 4889,
 'meet': 4432,
 'lunch': 4266,
 'den': 2250,
 'him': 3438,
 'already': 945,
 'lor': 4215,
 'or': 4974,
 'wan': 7371,
 'go': 3162,
 'da': 2148,
 'ge': 3101,
 'then': 6836,
 'confirm': 1962,
 'me': 4413,
 'asap': 1109,
 'are': 1072,
 'free': 2987,
 'now': 4846,
 'call': 1610,
 'hey': 3425,
 'no': 4804,
 'ad': 830,
 'crap': 2058,
 'nite': 4798,
 'was': 7390,
 'borin': 1451,
 'without': 7551,
 'ya': 7666,
 'boggy': 1432,
 'with': 7547,
 'boring': 1452,
 'biatch': 1366,
 'thanx': 6818,
 'but': 1576,
 'wait': 7353,
 'til': 6905,
 'nxt': 4870,
 'il': 3611,
 'ave': 1181,
 'reason': 5611,
 'the': 6824,
 'team': 6750,
 'budget': 1552,
 'available': 1178,
 'last': 4034,
 'they': 6848,
 'buy': 1581,
 'unsold': 7178,
 'players': 5243,
 'base': 1257,
 'rate': 5570,
 'our': 5006,
 'mobile': 4548,
 'number': 4859,
 'has': 3351,
 'won': 7577,
 '5000': 545,
 'to': 6942,
 'claim': 1823,
 'calls': 1624,
 'us': 7216,
 'back': 1218,
 'ring': 5789,
 'claims': 1825,
 'hot': 3508,
 'line': 4135,
 'on': 4935,
 '09050005321': 168,
 'arr': 1094,
 'birthday': 1387,
 'today': 6947,
 'wish': 7539,
 'get': 3122,
 'more': 4590,
 'oscar': 4995,
 'does': 2384,
 'she': 6079,
 'usually': 7230,
 'take': 6699,
 'fifteen': 2829,
 'fucking': 3033,
 'minutes': 4506,
 'respond': 5742,
 'yes': 7691,
 'question': 5523,
 'tell': 6768,
 'blake': 1399,
 'address': 837,
 'carlos': 1668,
 'wanted': 7378,
 'there': 6840,
 'lost': 4222,
 'and': 982,
 'he': 3373,
 'answering': 1007,
 'his': 3442,
 'phone': 5184,
 'thanks': 6814,
 'your': 7713,
 'message': 4463,
 'really': 5606,
 'appreciate': 1053,
 'sacrifice': 5874,
 'sure': 6631,
 'process': 5433,
 'direct': 2338,
 'pay': 5112,
 'will': 7517,
 'find': 2851,
 'out': 5009,
 'my': 4673,
 'way': 7412,
 'from': 3021,
 'test': 6794,
 'tomorrow': 6965,
 'in': 3641,
 'class': 1831,
 'do': 2375,
 'have': 3362,
 'day': 2188,
 'weekend': 7440,
 'ur': 7202,
 'cash': 1677,
 'balance': 1233,
 'currently': 2127,
 '500': 544,
 'pounds': 5342,
 'maximize': 4404,
 'send': 6008,
 '86688': 704,
 'only': 4947,
 '150p': 307,
 'msg': 4624,
 'cc': 1696,
 '08708800282': 87,
 'hg': 3427,
 'suite342': 6593,
 '2lands': 405,
 'row': 5833,
 'w1j6hl': 7339,
 'sir': 6186,
 'am': 955,
 'waiting': 7356,
 'once': 4939,
 'please': 5249,
 '22': 364,
 'days': 2189,
 'kick': 3930,
 'off': 4891,
 'euro2004': 2652,
 'be': 1289,
 'kept': 3916,
 'up': 7186,
 'date': 2181,
 'latest': 4040,
 'news': 4770,
 'results': 5755,
 'daily': 2156,
 'removed': 5696,
 'txt': 7100,
 'stop': 6495,
 '83222': 680,
 'accept': 795,
 'as': 1108,
 'brother': 1534,
 'sister': 6189,
 'lover': 4242,
 'dear1': 2199,
 'best1': 1347,
 'clos1': 1850,
 'lvblefrnd': 4277,
 'jstfrnd': 3862,
 'cutefrnd': 2138,
 'lifpartnr': 4113,
 'belovd': 1336,
 'swtheart': 6674,
 'bstfrnd': 1544,
 'rply': 5839,
 'means': 4420,
 'enemy': 2594,
 'hello': 3404,
 'boytoy': 1489,
 'geeee': 3103,
 'miss': 4514,
 'just': 3875,
 'woke': 7572,
 'were': 7461,
 'here': 3416,
 'bed': 1306,
 'cuddling': 2116,
 'love': 4237,
 'princess': 5409,
 'want': 7376,
 'make': 4332,
 'happy': 3341,
 'oops': 4956,
 'thk': 6861,
 'dun': 2491,
 'haf': 3301,
 'enuff': 2622,
 'check': 1756,
 'aiyar': 911,
 'sorry': 6331,
 'forgot': 2954,
 'bit': 1389,
 'smile': 6255,
 'hppnss': 3531,
 'drop': 2462,
 'tear': 6752,
 'sorrow': 6329,
 'part': 5087,
 'heart': 3386,
 'life': 4110,
 'like': 4120,
 'mine': 4493,
 'wil': 7514,
 'care': 1658,
 'forevr': 2947,
 'goodfriend': 3189,
 'ooh': 4953,
 '4got': 527,
 'gonna': 3185,
 'start': 6453,
 'belly': 1333,
 'dancing': 2163,
 'moseley': 4597,
 'weds': 7435,
 '30': 433,
 'join': 3841,
 'cafe': 1600,
 'too': 6979,
 'umma': 7131,
 'did': 2306,
 'say': 5924,
 'anything': 1023,
 'normally': 4832,
 'use': 7219,
 'drink': 2451,
 'water': 7404,
 'significant': 6160,
 'dont': 2410,
 'worry': 7603,
 'next': 4774,
 'sun': 6604,
 '1030': 263,
 'basic': 1259,
 'yoga': 7703,
 'course': 2041,
 'bugis': 1556,
 'we': 7417,
 'pilates': 5211,
 'intro': 3722,
 'sat': 5910,
 'lol': 4197,
 'actually': 829,
 'pic': 5196,
 'yourself': 7717,
 'right': 5783,
 'wanna': 7374,
 'see': 5981,
 'pose': 5318,
 'comb': 1910,
 'hair': 3305,
 'dryer': 2476,
 'something': 6306,
 'infront': 3680,
 'them': 6833,
 'santa': 5900,
 'calling': 1622,
 'would': 7610,
 'ones': 4942,
 'xmas': 7649,
 'eve': 2657,
 '09058094583': 179,
 'book': 1440,
 'dude': 2483,
 'im': 3616,
 'longer': 4203,
 'pisces': 5218,
 'an': 978,
 'aquarius': 1066,
 'haha': 3302,
 'better': 1352,
 'late': 4036,
 'than': 6810,
 'ever': 2664,
 'any': 1015,
 'could': 2029,
 'swing': 6668,
 'thought': 6872,
 'so': 6284,
 'come': 1912,
 'round': 5829,
 'dunno': 2493,
 'her': 3415,
 'faith': 2757,
 'makes': 4333,
 'things': 6853,
 'possible': 5326,
 'hope': 3488,
 'work': 7592,
 'beautiful': 1296,
 'may': 4405,
 'all': 935,
 'three': 6878,
 'this': 6860,
 'christmas': 1811,
 'merry': 4460,
 'ow': 5032,
 'dey': 2290,
 'paid': 5051,
 '60': 579,
 '400thousad': 490,
 'told': 6955,
 'how': 3521,
 'its': 3770,
 'difficult': 2319,
 'simple': 6169,
 'enter': 2611,
 'place': 5226,
 'talk': 6706,
 'english': 2602,
 'grins': 3248,
 'muhommad': 4645,
 'penny': 5138,
 'says': 5927,
 'across': 817,
 'sea': 5962,
 'watching': 7402,
 'tv': 7090,
 'boooo': 1445,
 'always': 953,
 'quit': 5529,
 'finished': 2859,
 'where': 7485,
 'anyway': 1026,
 'seriously': 6028,
 'hit': 3444,
 're': 5586,
 'because': 1300,
 'otherwise': 5000,
 'light': 4117,
 'armand': 1088,
 'vomiting': 7324,
 'aight': 902,
 'should': 6124,
 'plan': 5231,
 'later': 4039,
 'tonight': 6974,
 'yeah': 7680,
 'basically': 1260,
 'week': 7438,
 'away': 1194,
 'mom': 4568,
 'amp': 972,
 'before': 1317,
 'record': 5636,
 'one': 4941,
 'show': 6129,
 'leh': 4081,
 'still': 6482,
 'busy': 1575,
 'doing': 2397,
 'report': 5717,
 'yo': 7702,
 'parents': 5081,
 'gettin': 3127,
 'picked': 5198,
 'downstem': 2435,
 'ok': 4915,
 'chinese': 1794,
 'food': 2932,
 'fat': 2784,
 'paying': 5116,
 'lipo': 4150,
 'moon': 4588,
 'color': 1903,
 'dreams': 2447,
 'stars': 6451,
 'musical': 4663,
 'sms': 6266,
 'give': 3147,
 'warm': 7383,
 'peaceful': 5125,
 'sleep': 6222,
 'taking': 6703,
 'derek': 2265,
 'taylor': 6736,
 'walmart': 7368,
 'done': 2408,
 'leave': 4070,
 'mouse': 4609,
 'desk': 2271,
 'll': 4173,
 'text': 6798,
 'priscilla': 5416,
 'ready': 5596,
 'ah': 892,
 'well': 7454,
 'confuses': 1967,
 'doesn': 2386,
 'mag': 4315,
 'meeting': 4434,
 'avo': 1185,
 'some': 6299,
 'point': 5286,
 'painful': 5053,
 'personal': 5160,
 'try': 7063,
 'keep': 3909,
 'everybody': 2667,
 'nobody': 4807,
 'recognises': 5635,
 'alone': 942,
 'oh': 4910,
 'thats': 6823,
 'iam': 3573,
 'going': 3174,
 'alright': 946,
 'car': 1654,
 'gr8': 3215,
 'leaving': 4072,
 'congrats': 1968,
 'dear': 2198,
 'school': 5937,
 'plans': 5237,
 'lmao': 4174,
 'know': 3964,
 'shuhui': 6143,
 'bought': 1462,
 'ron': 5819,
 'present': 5387,
 'swatch': 6654,
 'watch': 7398,
 'full': 3040,
 'online': 4945,
 'need': 4732,
 'sent': 6018,
 'explain': 2722,
 'alle': 938,
 'mone': 4574,
 'eppolum': 2626,
 'oru': 4993,
 'pole': 5291,
 'allalo': 937,
 'battery': 1271,
 'mr': 4620,
 'adewale': 839,
 'uncle': 7140,
 'aka': 915,
 'egbon': 2547,
 'mall': 4340,
 'babe': 1210,
 'friend': 3006,
 'had': 3299,
 'cancel': 1637,
 'visit': 7309,
 'money': 4575,
 'wining': 7528,
 '946': 748,
 'wot': 7608,
 'eh': 2551,
 'kb': 3906,
 'liao': 4102,
 'huh': 3546,
 'customer': 2132,
 'total': 7002,
 'disappointment': 2347,
 'texted': 6802,
 'craziest': 2064,
 'guaranteed': 3269,
 '32000': 450,
 'award': 1192,
 'maybe': 4407,
 'even': 2659,
 '1000': 256,
 '0800': 46,
 '18': 322,
 'legitimat': 4079,
 'efreefone': 2545,
 'think': 6854,
 'must': 4665,
 'taken': 6700,
 'real': 5597,
 'valentine': 7242,
 'shopping': 6113,
 'first': 2869,
 'regret': 5667,
 'inform': 3676,
 'nhs': 4775,
 'made': 4311,
 'mistake': 4522,
 'never': 4761,
 'born': 1453,
 'yor': 7705,
 'local': 4181,
 'hospital': 3503,
 '2b': 389,
 'terminated': 6785,
 'inconvenience': 3653,
 'private': 5418,
 '2004': 353,
 'account': 806,
 'statement': 6460,
 '07742676969': 30,
 'shows': 6136,
 '786': 639,
 'unredeemed': 7176,
 'bonus': 1438,
 'points': 5287,
 '08719180248': 150,
 'identifier': 3594,
 'code': 1886,
 '45239': 512,
 'expires': 2720,
 'ding': 2332,
 'break': 1501,
 'fassyole': 2780,
 'blacko': 1397,
 'londn': 4199,
 'hi': 3429,
 'coming': 1918,
 'though': 6871,
 'didnt': 2309,
 'soon': 6323,
 'kisses': 3951,
 'xxx': 7656,
 'trouble': 7050,
 'while': 7491,
 'convincing': 2002,
 'tel': 6763,
 'twice': 7094,
 'neglect': 4741,
 'msgs': 4629,
 'read': 5592,
 'don': 2406,
 'massive': 4382,
 'pain': 5052,
 'ass': 1125,
 'rather': 5572,
 'involved': 3734,
 'about': 778,
 'further': 3052,
 'sounds': 6343,
 'gd': 3099,
 'wah': 7347,
 'yan': 7672,
 'jiu': 3830,
 'fast': 2781,
 '400': 488,
 'reward': 5771,
 'computer': 1947,
 'randomly': 5563,
 'loyal': 4252,
 'customers': 2134,
 'receive': 5622,
 '09066380611': 234,
 'hotel': 3509,
 'dusk': 2498,
 'game': 3070,
 'solve': 6297,
 'puzzles': 5509,
 'area': 1073,
 'thing': 6852,
 'chief': 1780,
 'bell': 1331,
 'royal': 5836,
 'june': 3871,
 'recieve': 5632,
 'tone': 6967,
 'within': 7550,
 '24hrs': 371,
 'terms': 6786,
 'conditions': 1957,
 'channel': 1729,
 'teletext': 6767,
 'pg': 5173,
 '750': 631,
 'headache': 3375,
 'trying': 7065,
 'figure': 2835,
 'trust': 7060,
 'math': 4389,
 'promise': 5447,
 'checking': 1759,
 'iq': 3743,
 'who': 7495,
 'stalk': 6439,
 'profiles': 5440,
 'feb': 2800,
 'dis': 2344,
 'valued': 7248,
 'frnds': 3015,
 'evn': 2679,
 'comes': 1914,
 'married': 4372,
 'person': 5158,
 'luv': 4271,
 'ignore': 3605,
 'lose': 4217,
 'evr': 2683,
 'tuition': 7079,
 'looking': 4210,
 'empty': 2583,
 'slots': 6238,
 'driving': 2459,
 'lessons': 4094,
 'computational': 1946,
 'science': 5939,
 'dat': 2179,
 'push': 5500,
 'saw': 5923,
 'burgundy': 1566,
 'captaining': 1653,
 'party': 5095,
 'boat': 1430,
 'cheers': 1764,
 'zogtorius': 7738,
 've': 7262,
 'been': 1311,
 'staring': 6449,
 'age': 884,
 'deciding': 2209,
 'whether': 7489,
 'settled': 6039,
 'new': 4765,
 'year': 7681,
 'wishin': 7542,
 'didn': 2308,
 'decided': 2208,
 'head': 3374,
 'laugh': 4042,
 'chit': 1798,
 'chat': 1746,
 'logon': 4194,
 'txting': 7105,
 'word': 7590,
 '8883': 723,
 'cm': 1867,
 'po': 5264,
 'box': 1467,
 '4217': 499,
 'london': 4200,
 'w1a': 7337,
 '6zf': 623,
 '16': 318,
 '118p': 276,
 'rcvd': 5583,
 'gauti': 3089,
 'sehwag': 5991,
 'odi': 4888,
 'series': 6026,
 'anytime': 1025,
 'network': 4756,
 'mins': 4502,
 '150': 305,
 'video': 7284,
 'five': 2875,
 'per': 5141,
 '08000776320': 48,
 'delivery': 2245,
 'replying': 5715,
 'boye': 1485,
 'changed': 1726,
 'door': 2417,
 'met': 4470,
 'alex': 927,
 'nichols': 4779,
 'middle': 4477,
 'turns': 7088,
 'dealing': 2197,
 'describe': 2267,
 'lucky': 4263,
 'awake': 1191,
 'noon': 4821,
 'seeing': 5982,
 'missed': 4515,
 'poor': 5308,
 'baby': 1213,
 'urfeeling': 7205,
 'bettersn': 1353,
 'probthat': 5432,
 'overdose': 5025,
 'careful': 1662,
 'spk': 6394,
 'sn': 6271,
 'lots': 4225,
 'lovejen': 4239,
 'sexy': 6048,
 'singles': 6181,
 'followed': 2924,
 'gender': 3106,
 'wither': 7549,
 '23f': 368,
 'gay': 3091,
 'men': 4451,
 '23g': 369,
 'print': 5410,
 'outs': 5017,
 'months': 4586,
 'ha': 3295,
 'joking': 3848,
 'blank': 1401,
 'again': 881,
 'yup': 7730,
 'serious': 6027,
 'studying': 6540,
 '85233': 698,
 'ringtone': 5792,
 'handed': 3318,
 'mega': 4437,
 'shop': 6111,
 'asda': 1110,
 'counts': 2036,
 'celebration': 1707,
 'indians': 3666,
 'india': 3664,
 'country': 2035,
 'swiss': 6669,
 'bank': 1243,
 'directors': 2341,
 'lac': 3999,
 'crore': 2085,
 'indian': 3665,
 'deposited': 2261,
 'banks': 1244,
 'which': 7490,
 'used': 7220,
 'taxless': 6734,
 'yrs': 7722,
 'jobs': 3835,
 'village': 7296,
 'delhi': 2240,
 'lane': 4019,
 'roads': 5803,
 'forever': 2946,
 'power': 5346,
 'suply': 6619,
 'social': 6287,
 'projects': 5444,
 'every': 2665,
 'citizen': 1819,
 'monthly': 4584,
 'world': 7598,
 'imf': 3621,
 'loan': 4179,
 'blocked': 1413,
 'rich': 5779,
 'politicians': 5293,
 'rights': 5786,
 'against': 882,
 'corrupt': 2020,
 'itna': 3768,
 'forward': 2965,
 'karo': 3899,
 'ki': 3928,
 'pura': 5494,
 'padhe': 5047,
 'pick': 5197,
 'rayan': 5576,
 'macleran': 4306,
 'true': 7055,
 'lov': 4235,
 'nevr': 4764,
 'unrecognized': 7175,
 'somone': 6314,
 'often': 4907,
 'mistakes': 4523,
 'valuing': 7250,
 'definitly': 2229,
 'undrstnd': 7152,
 'missing': 4517,
 'plus': 5261,
 'said': 5881,
 'grinule': 3249,
 'greet': 3244,
 'whenever': 7482,
 'speak': 6363,
 'booked': 1441,
 'lesson': 4093,
 'tmr': 6936,
 '930': 746,
 'wow': 7613,
 'firmware': 2867,
 'update': 7190,
 'help': 3406,
 'messages': 4465,
 'trip': 7045,
 'quite': 5530,
 'tiring': 6916,
 'uni': 7160,
 'starts': 6456,
 'cos': 2021,
 'modules': 4562,
 'jus': 3874,
 'concentrating': 1951,
 'final': 2847,
 'yr': 7721,
 'project': 5443,
 'until': 7184,
 'prob': 5425,
 'wif': 7508,
 'thinkin': 6855,
 'malaria': 4337,
 'relax': 5674,
 'children': 1785,
 'cant': 1645,
 'handle': 3320,
 'worse': 7604,
 'gastroenteritis': 3085,
 'takes': 6701,
 'enough': 2609,
 'replace': 5709,
 'loss': 4221,
 'temp': 6775,
 'reduce': 5645,
 'meds': 4430,
 'vomit': 7323,
 'self': 5996,
 'limiting': 4131,
 'illness': 3614,
 'few': 2821,
 'completely': 1939,
 '6times': 621,
 'movie': 4614,
 'xy': 7664,
 'wants': 7380,
 'set': 6035,
 'occurs': 4885,
 'hmm': 3455,
 'many': 4356,
 'unfortunately': 7157,
 'pics': 5201,
 'obviously': 4881,
 'arent': 1075,
 'cakes': 1603,
 'kinda': 3944,
 'fun': 3042,
 'tho': 6867,
 'hmmm': 3456,
 'guess': 3274,
 'tahan': 6694,
 'anot': 1000,
 'lo': 4176,
 'oso': 4996,
 'mapquest': 4358,
 'look': 4206,
 'usf': 7225,
 'dogwood': 2395,
 'drive': 2456,
 'tiny': 6912,
 'street': 6514,
 'parking': 5086,
 'lot': 4223,
 'meant': 4421,
 'yep': 7689,
 'jontin': 3852,
 'pls': 5256,
 'company': 1929,
 'name': 4691,
 'saibaba': 5880,
 'colany': 1893,
 'needa': 4733,
 'mcat': 4411,
 'study': 6539,
 'quitting': 5531,
 'least5times': 4069,
 'wudn': 7635,
 'much': 4641,
 'notice': 4841,
 'nah': 4685,
 'mind': 4491,
 'taunton': 6731,
 'ni8': 4776,
 'smth': 6270,
 'eat': 2520,
 'tunde': 7082,
 'wishing': 7543,
 'great': 3238,
 'abiola': 775,
 'credited': 2073,
 'activate': 824,
 'credit': 2072,
 '80488': 663,
 'cs': 2097,
 'www': 7638,
 'biz': 1393,
 'hours': 3515,
 'morning': 4594,
 'why': 7503,
 'finish': 2857,
 'home': 3474,
 'tot': 7001,
 'stay': 6464,
 'sch': 5935,
 'best': 1346,
 'dialogue': 2298,
 'cute': 2137,
 'reltnship': 5678,
 'wen': 7456,
 'die': 2310,
 'near': 4722,
 'body': 1431,
 'bcoz': 1285,
 'hands': 3321,
 'wipe': 7534,
 'tears': 6753,
 'gud': 3271,
 'finally': 2849,
 'came': 1629,
 'fix': 2876,
 'ceiling': 1703,
 'jamster': 3792,
 'crazy': 2065,
 'frog': 3020,
 'sound': 6341,
 'poly': 5295,
 'mad1': 4309,
 'mad2': 4310,
 '88888': 725,
 'gbp': 3095,
 'apply': 1048,
 'goodmorning': 3191,
 'decimal': 2210,
 'min': 4489,
 'talking': 6710,
 'bout': 1464,
 'early': 2509,
 'almost': 941,
 'engin': 2600,
 'dai': 2155,
 'downloaded': 2431,
 'exe': 2702,
 'file': 2838,
 'run': 5857,
 'after': 876,
 'installing': 3699,
 'ummmmmaah': 7134,
 'returns': 5764,
 'sweet': 6659,
 'very': 7274,
 'woo': 7585,
 'hoo': 3482,
 'six': 6199,
 'chances': 1724,
 'win': 7519,
 '100': 255,
 '20': 349,
 '000': 1,
 'csh11': 2100,
 '87575': 715,
 'cost': 2022,
 '6days': 613,
 'tsandcs': 7067,
 'hl': 3451,
 'info': 3675,
 'awesome': 1195,
 ...}

In [27]:
v.get_feature_names_out()[ 7481]

'when'

In [30]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7745,))

In [32]:
np.where(X_train_np[0]!= 0)

(array([1118, 1328, 1593, 1782, 2953, 3027, 3090, 3149, 3167, 3187, 3561,
        3751, 3763, 4164, 4240, 4786, 5714, 6491, 6820, 7042, 7474, 7481,
        7581]),)

In [36]:
X_train[:4][3760]

'GOD ASKED, "What is forgiveness?" A little child gave lovely reply, "It is d wonderful fruit that a tree gives when it is being hurt by a stone.. Good night......'

In [37]:
X_train_np[0][1782]

np.int64(1)

In [38]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [39]:
X_test_cv = v.transform(X_test)

In [41]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       954
           1       0.96      0.94      0.95       161

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [42]:
X_test.values

array(["naughty little thought: 'its better to flirt, flirt n flirt, rather than loving someone n gettin hurt, hurt n hurt...:-) Gud nyt",
       'If u dun drive then how i go 2 sch.',
       'Had your mobile 10 mths? Update to latest Orange camera/video phones for FREE. Save £s with Free texts/weekend calls. Text YES for a callback orno to opt out',
       ..., 'HEY THERE BABE, HOW U DOIN? WOT U UP 2 2NITE LOVE ANNIE X.',
       "Pass dis to all ur contacts n see wat u get! Red;i'm in luv wid u. Blue;u put a smile on my face. Purple;u r realy hot. Pink;u r so swt. Orange;i thnk i lyk u. Green;i realy wana go out wid u. Yelow;i wnt u bck. Black;i'm jealous of u. Brown;i miss you Nw plz giv me one color",
       "I'm used to it. I just hope my agents don't drop me since i've only booked a few things this year. This whole me in boston, them in nyc was an experiment."],
      shape=(1115,), dtype=object)

In [43]:
emails = ["naughty little thought: 'its better to flirt, flirt n flirt, rather than loving someone n gettin hurt, hurt n hurt...:-) Gud nyt"]

emails_cv = v.transform(emails)
model.predict(emails_cv)

array([0])

Pipe Line

In [44]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('model', MultinomialNB())
])

In [45]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('model', MultinomialNB())])

In [46]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       954
           1       0.96      0.94      0.95       161

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

Exersize

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [4]:

#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable
df = pd.read_csv(r"C:\Users\ruchi\Videos\Data_Science\NLP\Season2\IMDB Dataset.csv")


#2. print the shape of the data
print(df.shape)

#3. print top 5 datapoints
df.head()

(50000, 2)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
#creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative
df['Category'] = df['sentiment'].apply(lambda x: 1 if x =='positive' else 0)

In [6]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.

df['Category'].value_counts()

Category
1    25000
0    25000
Name: count, dtype: int64

In [7]:

#Do the 'train-test' splitting with test size of 20%

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.review, df.Category, test_size=0.2)

In [9]:
#1. create a pipeline object
clf = Pipeline([
    ('vectorizer', CountVectorizer()),                                                    #initializing the vectorizer
    ('random_forest', (RandomForestClassifier(n_estimators=50, criterion='entropy')))      #using the RandomForest classifier
])



#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.84      0.84      4984
           1       0.84      0.83      0.83      5016

    accuracy                           0.83     10000
   macro avg       0.83      0.83      0.83     10000
weighted avg       0.83      0.83      0.83     10000

In [10]:
#1. create a pipeline object
clf = Pipeline([
                
     ('vectorizer', CountVectorizer()),   
      ('KNN', (KNeighborsClassifier(n_neighbors=10, metric = 'euclidean')))   #using the KNN classifier with 10 neighbors 
])


#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.65      0.65      4984
           1       0.65      0.65      0.65      5016

    accuracy                           0.65     10000
   macro avg       0.65      0.65      0.65     10000
weighted avg       0.65      0.65      0.65     10000

In [11]:

#1. create a pipeline object
clf = Pipeline([
                
     ('vectorizer', CountVectorizer()),   
      ('Multi NB', MultinomialNB())   #using the Multinomial Naive Bayes classifier 
])


#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      4984
           1       0.87      0.82      0.84      5016

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000

### Can you write some observations of why model like KNN fails to produce good results unlike RandomForest and MultinomialNB?
As Machine learning algorithms does not work on Text data directly, we need to convert them into numeric vector and feed that into models while training.
In this process, we convert text into a very high dimensional numeric vector using the technique of Bag of words.
Model like K-Nearest Neighbours(KNN) doesn't work well with high dimensional data because with large number of dimensions, it becomes difficult for the algorithm to calculate distance in each dimension. In higher dimensional space, the cost to calculate distance becomes expensive and hence impacts the performance of model.
The easy calculation of probabilities for the words in corpus(Bag of words) and storing them in contigency table is the major reason for the Multinomial NaiveBayes to be a text classification friendly algorithm.
As Random Forest uses Bootstrapping(Row and column Sampling) with many decision tree and overcomes the high variance and overfitting of high dimensional data and also uses feature importance of words for better classifing the categories.
Machine Learning is like trial and error scientific method, where we keep trying all the possible algorithms we have and select the one which give good results and satisfy the requirements like latency, interpretability etc.